{% set name = "QuantLib" %}
{% set version = "1.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lballabio/QuantLib/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4810d789261eb36423c7d277266a6ee3b28a3c05af1ee0d45544ca2e0e8312bd
  patches:
    - 0001-Remove-use-of-BOOST_ALL_DYN_LINK.patch

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('quantlib', max_pin='x') }}  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - autoconf  # [unix]
    - automake  # [unix]
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - libboost-devel
  run:

test:
  commands:
    - quantlib-test-suite --log_level=message  # [win]
    - cd build && ./test-suite/quantlib-test-suite --log_level=message  # [unix]

about:
  home: https://github.com/lballabio/QuantLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The QuantLib C++ library
  description: The QuantLib project (https://www.quantlib.org) is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  recipe-maintainers:
    - timkpaine
